---

- name: Enable connections to HTTP port
  seport:
    ports: '{{ hybris_selinux_ports }}'
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_selinux.status == "enabled"
    - ansible_selinux.mode != "disabled"
  become: true
