---
- name: Enable EPEL repository
  command: amazon-linux-extras install epel -y
  register: install_package
  until: install_package.rc == 0
  retries: 3
  delay: 5
  become: true
  when: ansible_distribution == 'Amazon' and ansible_distribution_major_version == '2'
