---
- name: Enable EPEL repository
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  register: install_package
  until: install_package is succeeded
  become: true
